# Generated by Django 6.1.1 on 2026-09-15 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElementoPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('alternativa', 'Alternativa'), ('premisa', 'Premisa'), ('hueco', 'Palabra faltante'), ('distractor', 'Palabra distractora (no va en ningún hueco)')], max_length=15)),
                ('contenido', models.CharField(max_length=300)),
                ('es_correcto', models.BooleanField(default=False)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('posicion_hueco', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('contextual', 'Contextual (5 alternativas)'), ('vf_premisas', 'V/F con 4 premisas (5 alternativas)'), ('cuantas_correctas', 'Cuántas son correctas (4 premisas)'), ('inferencial', 'Inferencial (5 alternativas)'), ('abierta', 'Pregunta abierta'), ('completar', 'Completar oración (arrastrar palabras)')], max_length=25)),
                ('enunciado', models.TextField()),
                ('dificultad', models.PositiveSmallIntegerField(default=1)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaAbierta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_modelo', models.TextField(blank=True)),
            ],
        ),
    ]
