# Generated by Django 6.1.1 on 2026-09-15 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0002_initial'),
        ('preguntas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='academico.tema'),
        ),
        migrations.AddField(
            model_name='elementopregunta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementos', to='preguntas.pregunta'),
        ),
        migrations.AddField(
            model_name='preguntaabierta',
            name='pregunta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abierta', to='preguntas.pregunta'),
        ),
    ]
