# Generated by Django 6.1 on 2026-08-31 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_remove_usuario_dni_alter_usuario_rol_perfildocente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('orden', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('orden', models.PositiveSmallIntegerField()),
                ('icono', models.CharField(blank=True, max_length=50)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas', to='academico.etapa')),
                ('tema_previo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siguientes', to='academico.tema')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ProgresoTema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desbloqueado', models.BooleanField(default=False)),
                ('completado', models.BooleanField(default=False)),
                ('estrellas', models.PositiveSmallIntegerField(default=0)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='users.perfilestudiante')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.tema')),
            ],
            options={
                'unique_together': {('estudiante', 'tema')},
            },
        ),
    ]
