# Generated by Django 6.1 on 2026-09-01 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
        ('users', '0002_remove_usuario_dni_alter_usuario_rol_perfildocente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('docente', models.ForeignKey(limit_choices_to={'rol': 'docente'}, on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to=settings.AUTH_USER_MODEL)),
                ('estudiantes', models.ManyToManyField(blank=True, related_name='secciones', to='users.perfilestudiante')),
            ],
        ),
    ]
