# Generated by Django 6.1.1 on 2026-09-15 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='progresotema',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='users.perfilestudiante'),
        ),
        migrations.AddField(
            model_name='seccion',
            name='docente',
            field=models.ForeignKey(limit_choices_to={'rol': 'docente'}, on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seccion',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, related_name='secciones', to='users.perfilestudiante'),
        ),
        migrations.AddField(
            model_name='tema',
            name='etapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas', to='academico.etapa'),
        ),
        migrations.AddField(
            model_name='tema',
            name='tema_previo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siguientes', to='academico.tema'),
        ),
        migrations.AddField(
            model_name='progresotema',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.tema'),
        ),
        migrations.AlterUniqueTogether(
            name='progresotema',
            unique_together={('estudiante', 'tema')},
        ),
    ]
