# Generated by Django 6.1 on 2026-09-01 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0002_seccion'),
        ('preguntas', '0001_initial'),
        ('users', '0002_remove_usuario_dni_alter_usuario_rol_perfildocente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentoTema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciado', models.DateTimeField(auto_now_add=True)),
                ('finalizado', models.DateTimeField(blank=True, null=True)),
                ('vidas_restantes', models.PositiveSmallIntegerField(default=5)),
                ('completado', models.BooleanField(default=False)),
                ('racha_errores_actual', models.PositiveSmallIntegerField(default=0)),
                ('racha_errores_maxima', models.PositiveSmallIntegerField(default=0)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='users.perfilestudiante')),
                ('preguntas_asignadas', models.ManyToManyField(related_name='intentos', to='preguntas.pregunta')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.tema')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_correcta', models.BooleanField()),
                ('payload', models.JSONField()),
                ('tiempo_respuesta_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('intento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='intentos.intentotema')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preguntas.pregunta')),
            ],
        ),
    ]
