# Generated by Django 6.1.1 on 2026-09-15 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntentoTema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciado', models.DateTimeField(auto_now_add=True)),
                ('finalizado', models.DateTimeField(blank=True, null=True)),
                ('vidas_restantes', models.PositiveSmallIntegerField(default=5)),
                ('completado', models.BooleanField(default=False)),
                ('racha_errores_actual', models.PositiveSmallIntegerField(default=0)),
                ('racha_errores_maxima', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_correcta', models.BooleanField()),
                ('payload', models.JSONField()),
                ('tiempo_respuesta_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
