# Generated by Django 6.1.1 on 2026-09-15 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0002_initial'),
        ('intentos', '0001_initial'),
        ('preguntas', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intentotema',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='users.perfilestudiante'),
        ),
        migrations.AddField(
            model_name='intentotema',
            name='preguntas_asignadas',
            field=models.ManyToManyField(related_name='intentos', to='preguntas.pregunta'),
        ),
        migrations.AddField(
            model_name='intentotema',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.tema'),
        ),
        migrations.AddField(
            model_name='respuestaestudiante',
            name='intento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='intentos.intentotema'),
        ),
        migrations.AddField(
            model_name='respuestaestudiante',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preguntas.pregunta'),
        ),
    ]
