# Generated by Django 6.1.1 on 2026-09-21 03:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilestudiante',
            name='correo',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='perfilestudiante',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilestudiante',
            name='horas_minimas',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilestudiante',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='perfilestudiante',
            name='via_contacto',
            field=models.CharField(choices=[('email', 'Correo'), ('telefono', 'Teléfono')], default='email', max_length=10),
        ),
        migrations.AlterField(
            model_name='perfilestudiante',
            name='nombre_perfil',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator("^[^\\W\\d_ \\-']{2,100}$", 'Solo letras y espacios.')]),
        ),
    ]
