# Generated by Django 6.1.1 on 2026-09-21 03:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_perfilestudiante_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilestudiante',
            name='nombre_perfil',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator("^(?:[^\\W\\d_]|[ \\-\\']){2,100}$", 'Solo letras y espacios.')]),
        ),
    ]
